### ISSUE TITLE
What is this project?

### ISSUE THREAD

**Issue by TheCurle** [DarkCoderSc/SubSeven#1]
I found this repository through [this tweet](https://twitter.com/DarkCoderSc/status/1564185343624093699), which just says "SubSeven Legacy is now open source". 

The repo description just says "SubSeven Legacy Official Source Code Repository", and the README just describes it as "SubSeven Legacy is a complete remake and improvement of the infamous SubSeven (a.k.a Sub7) program from late 90s", along with a bunch of history and unrelated data.

Nowhere is it described what the project actually is, what it does, what problem it was intended to describe, not even a two-word passing mention of its primary purpose.

You should probably consider adding a sentence or two explaining what it is :)

**Comment by DarkCoderSc** [comment]
I will clarify the purpose of the project asap ;) 

Thanks for the feedback

**Comment by 0xsyr0** [comment]
There is so much nostalgia! I f*in love it! Thank you very much for this remake! Already starred :)
