### ISSUE TITLE
I need help to install 

### ISSUE THREAD

**Issue by DannyBrock123** [DarkCoderSc/SubSeven#3]
Hi, I'm trying to download sub7 but Idk what to do

**Comment by therealgorgan** [comment]
![image](https://user-images.githubusercontent.com/33201476/226064277-567bd9f6-9058-497f-9154-26bb80250d31.png)

I have a copy of the server and the viewer binaries if someone needs, they don't seem to be available here anymore... I wonder if someone has taken over to do something nefarious or something weird HMMMMM

**Comment by DarkCoderSc** [comment]
I will compile the server and release it asap.

Regards

**Comment by DarkCoderSc** [comment]
Service source code has been released, you can now compile everything yourself then create your own setup for installation ;)
